---
name: CI tests
on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

env:
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libdbus-1-dev
          version: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - run: |
          cargo install --locked cargo-deny@0.13.7 || true
          cargo install --locked cargo-udeps@0.1.35 || true
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: cargo build --verbose
      - run: cargo deny check
      - run: rustup toolchain install nightly
      - run: cargo +nightly udeps
